name: Update SPEC 0 dependencies

on:
  schedule:
    # Every Sunday at midnight UTC
    - cron: "0 0 * * SUN"
  # On demand:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: scientific-python/spec0-action@fa33c6c11eaf1dc244b17df5537875e2eab11e82
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
